### ISSUE TITLE
Support React 18

### ISSUE THREAD

**Issue by nikeee** [davidhu2000/react-spinners#463] opened 2022-03-29 20:12 UTC
React 18 released:
https://github.com/facebook/react/releases/tag/v18.0.0

Is this library compatible with React 18 despite the warning that's currently printed when installing react-spinners?

**Comment by RubenVerster** [comment] 2022-04-09 22:43
Just install it like this for now please
npm install --save react-spinners --legacy-peer-deps

**Comment by nikeee** [comment] 2022-04-10 01:38
Yes, that might work. However, as seen in your instructions, `--legacy-peer-deps` uses a legacy mode, which should be avoided.
Fixing this upstream would be appropriate.

There is a PR for upgrading the dependency: #464

**Comment by davidhu2000** [comment] 2022-05-03 03:43
try 0.12.0-alpha.3 and see if the issue is resolved

**Comment by davidhu2000** [comment] 2022-05-03 04:00
oof, this might be more compcliated than expected given enzyme doesn't have an adapter for react 18

**Comment by RubenVerster** [comment] 2022-05-03 09:33
> Yes, that might work. However, as seen in your instructions, `--legacy-peer-deps` uses a legacy mode, which should be avoided. Fixing this upstream would be appropriate.
> 
> There is a PR for upgrading the dependency: #464

I know man... but this is the current fix for the issue right now
Once the PR has been merged in, they will come and tell us that the issue has an official fix :P

**Comment by aperalta1431** [comment] 2022-05-14 20:43
I appreciate the above solution but it should be avoided. Besides the above solution involves making changes to the pipeline to support such legacy mode if we still want to proceed with it which is not suitable in an enterprise setting. Nonetheless, the library is a time saver and I will be waiting for an update on this.

**Comment by Ali-Aref** [comment] 2022-05-15 13:41
any updates ?

**Comment by davidhu2000** [comment] 2022-05-16 01:17
v0.12.0 is released with this fix.

**Closed by davidhu2000** 2022-05-16 01:17 UTC
Labels: feature_request
