### ISSUE TITLE
Using only specific loader type without importing whole spinner

### ISSUE THREAD

**Issue by archansel** [davidhu2000/react-spinners#23] opened 2017-12-28 08:32 UTC
Hi, is there any way to load only one specific loader without the whole spinner being bundled. Something like what `lodash` did, for example:
```
import BarLoader from 'react-spinners/bar-loader';
```

**Comment by ThomasBem** [comment] 2018-02-13 06:28
Would also be interested in this! Currently react-spinners is 9% of our small apps total bundle size.

Love the spinners though! RingLoader is awesome :)

**Comment by davidhu2000** [comment] 2018-04-22 21:39
@archansel @ThomasBem, I ran a quick test, looks you like can import just one. 

`import BarLoader from 'react-spinners/dist/spinners/BarLoader';`

Trying to see how I can remove the `/dist/spinners` part`. 

Can you guys give that a try and see if the bundle size is reduced?

**Comment by Dman757** [comment] 2018-07-20 17:32
Figured I would chime in to confirm this worked on my end. I used `source-map-explorer` for a quick test. https://www.npmjs.com/package/source-map-explorer

![Before](https://user-images.githubusercontent.com/4275720/43016571-13cfaec2-8c08-11e8-9428-b585f1699a30.png)

![After](https://user-images.githubusercontent.com/4275720/43016584-20e470ca-8c08-11e8-8769-1281ac9caa3a.png)

**Comment by davidhu2000** [comment] 2018-08-11 04:07
@GuillaumeCisco Just merged in your PR, but looks like single loader import isn't working. 

I'm looking at possible solutions, not sure why. I had to deprecate `0.4.0`. We need to push out a patch for this.

**Comment by davidhu2000** [comment] 2018-08-11 04:13
I just published a patch 0.4.1 that removes the single loader import from the readme. So hopefully very few people uses 0.4.0.

**Comment by davidhu2000** [comment] 2018-08-11 04:26
looks like the issue is you need to `import BarLoader from 'react-spinners/dist/BarLoader';`

**Comment by GuillaumeCisco** [comment] 2018-08-11 08:11
Dist folder should not exist. Check the way the build work.

--
Guillaume Cisco

**Comment by davidhu2000** [comment] 2018-08-11 17:58
This is fixed in `>0.4.2`

**Closed by davidhu2000** 2018-08-11 17:58 UTC
Labels: feature request

**Comment by ThomasBem** [comment] 2018-09-17 11:07
We came back to our app recently where we use one of your spinners as our main loading animation. Updated to 0.4.3 and changed the import like you said and now our bundle size dropped by 50KB.

Just wanted to say thanks! 👍

**Comment by alexmironof** [comment] 2019-03-01 14:04
@davidhu2000 Can't use this import method with typescript. I've got error: `Could not find a declaration file for module 'react-spinners/GridLoader'.`

**Comment by davidhu2000** [comment] 2019-03-01 17:37
hmm, @alexmironof can you open a new issue? This feels like a different issue that the current issue.
