### ISSUE TITLE
GridLoader is not displayed in grid

### ISSUE THREAD

**Issue by GuillaumeDesforges** [davidhu2000/react-spinners#386] opened 2021-03-04 13:52 UTC
**Describe the bug**
The GridLoader is not displayed in grid, but in one line.

**To Reproduce**
1. Use GridLoader in any react project.

**Expected behavior**
GridLoader dots should be displayed in a 3x3 grid, not on one unique line.

**Screenshots**

![image](https://user-images.githubusercontent.com/1882000/109973456-b24c2380-7cf8-11eb-97e8-59acede84295.png)

**Additional context**
Must be because of https://github.com/davidhu2000/react-spinners/issues/159

Bug was not there in version `0.9.0` (I'm using this version to fix the issue temporarily).

**Possible fix**
Use css to display as block.

**Comment by davidhu2000** [comment] 2021-07-05 15:33
I'm not able to reproduce via the demo site. Can you show me what the css looks like? I wonder if the css is inheriting something from the parent

**Comment by GuillaumeDesforges** [comment] 2021-07-05 15:46
Sorry, I'm not on this projet anymore, and don't have the code anymore :/

**Comment by davidhu2000** [comment] 2021-07-05 19:30
i'll just close this issue for now and we can reopen with other reports.

**Comment by twschiller** [comment] 2021-07-11 01:38
@davidhu2000 Thanks for your work on the library!

We have the same issue with the GridLoader as was originally reported, and reverting to 0.9.0 fixes the problem. We'll report back with anything we find that might be the cause

Could you re-open in the meantime?

https://github.com/pixiebrix/pixiebrix-extension/issues/755

**Comment by davidhu2000** [comment] 2022-05-22 21:54
```tsx
import GridLoader from "react-spinners/GridLoader";

const DEFAULT_STYLE = {
  margin: "auto", // Center
  padding: "20px",
  display: "flex",
  justifyContent: "center"
};

export default function App() {
  return (
    <div style={DEFAULT_STYLE} data-testid="loader">
      <GridLoader />
    </div>
  );
}
````

@twschiller I tried to reproduce but couldn't. this is a copy/paste the Loader implementation. 

I am able to reproduce by adding a with override like

```tsx
<GridLoader css={{ width: undefined }} />
```

can ou check the css and see if that happens? did the default width get overwritten?

**Comment by davidhu2000** [comment] 2022-05-22 22:03
@twschiller can you try `0.13.0-alpha.5` and see if that resolves your issue?

**Comment by fregante** [comment] 2022-05-23 09:22
I tried updating from 0.9.0 and the loader is completely broken/hidden:

<img width="1189" alt="Screen Shot 17" src="https://user-images.githubusercontent.com/1402241/169743417-28fdfbf4-6e27-4392-b4e7-7deee948aa4b.png">

It should look like this:

<img width="863" alt="Screen Shot 18" src="https://user-images.githubusercontent.com/1402241/169743505-f2d09793-cdb1-4adf-bcdd-603abeafc05c.png">

I don't know if I missed some required changes, I'm just calling it as `<GridLoader />` but it's not appearing anywhere in my extension.

**Comment by davidhu2000** [comment] 2022-05-26 05:22
turns out you can't do inline style with `important` tag :)

**Comment by davidhu2000** [comment] 2022-05-26 05:44
@twschiller @GuillaumeDesforges can you try on `0.13.0-beta.3`? i think i fixed the issue.

**Comment by davidhu2000** [comment] 2022-05-26 06:30
Meant to tag @fregante :). Please give 0.13.0-beta.3 a try and see if it works

**Comment by fregante** [comment] 2022-05-27 15:36
I think it's finally working, but I'm getting this TypeScript error in your latest beta.It's probably because I'm on React 17 and am using its types.

```ts
node_modules/react-spinners/helpers/props.d.ts:3:11 - error TS2430: Interface 'CommonProps' incorrectly extends interface 'ClassAttributes<HTMLSpanElement> & HTMLAttributes<HTMLSpanElement>'.
  Type 'CommonProps' is not assignable to type 'HTMLAttributes<HTMLSpanElement>'.
    Types of property 'css' are incompatible.
      Type 'CSSProperties' is not assignable to type 'InterpolationWithTheme<any>'.
        Type 'Properties<string | number, string & {}>' is not assignable to type 'ObjectInterpolation<undefined>'.
          Types of property 'columnCount' are incompatible.
            Type 'ColumnCount' is not assignable to type 'ColumnCountProperty | ColumnCountProperty[] | ("auto" | Globals)[]'.
              Type 'string & {}' is not assignable to type 'ColumnCountProperty | ColumnCountProperty[] | ("auto" | Globals)[]'.
                Type 'String' is missing the following properties from type '("auto" | Globals)[]': pop, push, join, reverse, and 21 more.

3 interface CommonProps extends DetailedHTMLProps<HTMLAttributes<HTMLSpanElement>, HTMLSpanElement> {
```

**Comment by davidhu2000** [comment] 2022-06-03 05:51
Hmm, that look more like @emotion error? Maybe I need to rename the css prop to styleOverride or something. See if that helps

**Comment by davidhu2000** [comment] 2022-06-05 01:06
seems related to https://github.com/emotion-js/emotion/issues/1800?

**Comment by twschiller** [comment] 2022-06-06 11:08
> altho I don't see emotion in your repo, can you try deleting node_modules and reinstall everything? thinking maybe the prior installation is causing some conflicts

We include react-select in our project, which depends on emotion for styling: 
```
pixiebrix/extension@1.6.5-alpha.1 /Users/tschiller/projects/pixiebrix-extension
└─┬ react-select@5.3.2
  └── @emotion/react@11.9.0
```

Will have to track down which emotion release the fix for https://github.com/emotion-js/emotion/issues/1800 would have been rolled into

**Comment by davidhu2000** [comment] 2022-06-06 15:30
Let me know what you find. Given the number of projects using emotion, I'm tempted to rename the prop to avoid conflicts.

**Comment by davidhu2000** [comment] 2022-06-07 05:12
decided that renaming the prop made sense. it was only called `css` to match `emotion`. and now that emotion is removed, css might just cause confusion. https://github.com/davidhu2000/react-spinners/pull/524

@twschiller  want to give `0.13.0-beta.5` a shot and see if the type issue is resolved?

**Comment by twschiller** [comment] 2022-06-07 12:38
@davidhu2000 Thanks! It's working but the grid loader animation is a bit jumpy (not smooth) compared to `0.9.0`. Any ideas what might cause that? Will post a video later today

**Comment by davidhu2000** [comment] 2022-06-07 17:43
Yeah a video will be helpful. Given this is a total rewrite of the component, wouldn't be surprised if I missed a thing or two

**Comment by davidhu2000** [comment] 2022-06-08 04:19
so comparing the code before 
https://github.com/davidhu2000/react-spinners/blob/aee6124bcf6a603983d8eafbe334c97ad32d8bd2/src/GridLoader.tsx

vs  current

https://github.com/davidhu2000/react-spinners/blob/main/src/GridLoader.tsx
nothing is jumping out at me that could suggest the choppiness. 

altho the animation is based on a random number, maybe sometimes it looks choppy and ok other times?

**Comment by twschiller** [comment] 2022-06-17 17:58
Apologies for the delay, we were in crunch on a release the past couple weeks. Here's a Loom of the issue: https://www.loom.com/share/553454bd82fc471f8ecbd81b6a905b09

If I just throw it into Storybook, I don't see the jumpiness. So I think it has to do with re-renders/remounts. We might have to memoize the component. (The jumpiness is probably on our side)

With the `0.13.0-beta.5` we're still [having to do a CSS fix for the GridLoader not being displayed in a grid](https://github.com/pixiebrix/pixiebrix-extension/blob/621acc6e4e74532cad0a934f7d3f8d22f75360d5/src/components/Loader.tsx#L27-L27)

If we don't do that, we're still seeing the bug from the original ticket:
![image](https://user-images.githubusercontent.com/1879821/174352694-ea25bd09-49be-4296-9ff8-0c1d74b4f400.png)

I double-checked I'm on the right version:
![image](https://user-images.githubusercontent.com/1879821/174352819-3111fee4-22ad-4499-9cd8-532c924debe2.png)

**Comment by davidhu2000** [comment] 2022-06-25 22:07
actually i see that on my side in storybook as well. Will see what i can figure out

**Comment by davidhu2000** [comment] 2022-06-25 22:12
looks like adding `display: 'inline-block'` resolves the issue for me. @twschiller , Can you try beta.6 and see if it works?

**Comment by twschiller** [comment] 2022-06-27 02:23
> Can you try 0.13.0 and see if it works?

@davidhu2000 Thanks, looks like this version fixes the line break problem

**Closed** 2022-06-27 03:58 UTC
Labels: bug

**Comment by patrikw1** [comment] 2023-07-31 20:57
Turns out for me it was inherited white-space nowrap from bootstap's navbar brand

`white-space: normal` do it for me
